// Generated by gencpp from file thi_vision/track.msg
// DO NOT EDIT!


#ifndef THI_VISION_MESSAGE_TRACK_H
#define THI_VISION_MESSAGE_TRACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <thi_vision/pose.h>

namespace thi_vision
{
template <class ContainerAllocator>
struct track_
{
  typedef track_<ContainerAllocator> Type;

  track_()
    : track()  {
    }
  track_(const ContainerAllocator& _alloc)
    : track(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::thi_vision::pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::thi_vision::pose_<ContainerAllocator> >> _track_type;
  _track_type track;





  typedef boost::shared_ptr< ::thi_vision::track_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thi_vision::track_<ContainerAllocator> const> ConstPtr;

}; // struct track_

typedef ::thi_vision::track_<std::allocator<void> > track;

typedef boost::shared_ptr< ::thi_vision::track > trackPtr;
typedef boost::shared_ptr< ::thi_vision::track const> trackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thi_vision::track_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thi_vision::track_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::thi_vision::track_<ContainerAllocator1> & lhs, const ::thi_vision::track_<ContainerAllocator2> & rhs)
{
  return lhs.track == rhs.track;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::thi_vision::track_<ContainerAllocator1> & lhs, const ::thi_vision::track_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace thi_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::thi_vision::track_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thi_vision::track_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thi_vision::track_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thi_vision::track_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thi_vision::track_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thi_vision::track_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thi_vision::track_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c10583178550886efa4f5156f56c1e6";
  }

  static const char* value(const ::thi_vision::track_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c10583178550886ULL;
  static const uint64_t static_value2 = 0xefa4f5156f56c1e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::thi_vision::track_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thi_vision/track";
  }

  static const char* value(const ::thi_vision::track_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thi_vision::track_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose[] track\n"
"\n"
"================================================================================\n"
"MSG: thi_vision/pose\n"
"position point\n"
"orientation angle\n"
"\n"
"================================================================================\n"
"MSG: thi_vision/position\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
"================================================================================\n"
"MSG: thi_vision/orientation\n"
"float32 a\n"
"float32 b\n"
"float32 c\n"
;
  }

  static const char* value(const ::thi_vision::track_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thi_vision::track_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.track);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct track_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thi_vision::track_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thi_vision::track_<ContainerAllocator>& v)
  {
    s << indent << "track[]" << std::endl;
    for (size_t i = 0; i < v.track.size(); ++i)
    {
      s << indent << "  track[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::thi_vision::pose_<ContainerAllocator> >::stream(s, indent + "    ", v.track[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // THI_VISION_MESSAGE_TRACK_H
