// Generated by gencpp from file thi_vision/visionTracks.msg
// DO NOT EDIT!


#ifndef THI_VISION_MESSAGE_VISIONTRACKS_H
#define THI_VISION_MESSAGE_VISIONTRACKS_H

#include <ros/service_traits.h>


#include <thi_vision/visionTracksRequest.h>
#include <thi_vision/visionTracksResponse.h>


namespace thi_vision
{

struct visionTracks
{

typedef visionTracksRequest Request;
typedef visionTracksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visionTracks
} // namespace thi_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::thi_vision::visionTracks > {
  static const char* value()
  {
    return "54640a39f52ffd596022a5e1d0dc6ffe";
  }

  static const char* value(const ::thi_vision::visionTracks&) { return value(); }
};

template<>
struct DataType< ::thi_vision::visionTracks > {
  static const char* value()
  {
    return "thi_vision/visionTracks";
  }

  static const char* value(const ::thi_vision::visionTracks&) { return value(); }
};


// service_traits::MD5Sum< ::thi_vision::visionTracksRequest> should match
// service_traits::MD5Sum< ::thi_vision::visionTracks >
template<>
struct MD5Sum< ::thi_vision::visionTracksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::thi_vision::visionTracks >::value();
  }
  static const char* value(const ::thi_vision::visionTracksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::thi_vision::visionTracksRequest> should match
// service_traits::DataType< ::thi_vision::visionTracks >
template<>
struct DataType< ::thi_vision::visionTracksRequest>
{
  static const char* value()
  {
    return DataType< ::thi_vision::visionTracks >::value();
  }
  static const char* value(const ::thi_vision::visionTracksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::thi_vision::visionTracksResponse> should match
// service_traits::MD5Sum< ::thi_vision::visionTracks >
template<>
struct MD5Sum< ::thi_vision::visionTracksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::thi_vision::visionTracks >::value();
  }
  static const char* value(const ::thi_vision::visionTracksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::thi_vision::visionTracksResponse> should match
// service_traits::DataType< ::thi_vision::visionTracks >
template<>
struct DataType< ::thi_vision::visionTracksResponse>
{
  static const char* value()
  {
    return DataType< ::thi_vision::visionTracks >::value();
  }
  static const char* value(const ::thi_vision::visionTracksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THI_VISION_MESSAGE_VISIONTRACKS_H
