// Generated by gencpp from file kuka_tcp/kukaTrackResponse.msg
// DO NOT EDIT!


#ifndef KUKA_TCP_MESSAGE_KUKATRACKRESPONSE_H
#define KUKA_TCP_MESSAGE_KUKATRACKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_tcp
{
template <class ContainerAllocator>
struct kukaTrackResponse_
{
  typedef kukaTrackResponse_<ContainerAllocator> Type;

  kukaTrackResponse_()
    : ok(false)  {
    }
  kukaTrackResponse_(const ContainerAllocator& _alloc)
    : ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> const> ConstPtr;

}; // struct kukaTrackResponse_

typedef ::kuka_tcp::kukaTrackResponse_<std::allocator<void> > kukaTrackResponse;

typedef boost::shared_ptr< ::kuka_tcp::kukaTrackResponse > kukaTrackResponsePtr;
typedef boost::shared_ptr< ::kuka_tcp::kukaTrackResponse const> kukaTrackResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuka_tcp::kukaTrackResponse_<ContainerAllocator1> & lhs, const ::kuka_tcp::kukaTrackResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuka_tcp::kukaTrackResponse_<ContainerAllocator1> & lhs, const ::kuka_tcp::kukaTrackResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuka_tcp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::kuka_tcp::kukaTrackResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_tcp/kukaTrackResponse";
  }

  static const char* value(const ::kuka_tcp::kukaTrackResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"\n"
;
  }

  static const char* value(const ::kuka_tcp::kukaTrackResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kukaTrackResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_tcp::kukaTrackResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_tcp::kukaTrackResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_TCP_MESSAGE_KUKATRACKRESPONSE_H
