// Generated by gencpp from file node_manager/nodeInfo.msg
// DO NOT EDIT!


#ifndef NODE_MANAGER_MESSAGE_NODEINFO_H
#define NODE_MANAGER_MESSAGE_NODEINFO_H

#include <ros/service_traits.h>


#include <node_manager/nodeInfoRequest.h>
#include <node_manager/nodeInfoResponse.h>


namespace node_manager
{

struct nodeInfo
{

typedef nodeInfoRequest Request;
typedef nodeInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nodeInfo
} // namespace node_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::node_manager::nodeInfo > {
  static const char* value()
  {
    return "7752f5a8c2441ad5def7b480e5f4374d";
  }

  static const char* value(const ::node_manager::nodeInfo&) { return value(); }
};

template<>
struct DataType< ::node_manager::nodeInfo > {
  static const char* value()
  {
    return "node_manager/nodeInfo";
  }

  static const char* value(const ::node_manager::nodeInfo&) { return value(); }
};


// service_traits::MD5Sum< ::node_manager::nodeInfoRequest> should match
// service_traits::MD5Sum< ::node_manager::nodeInfo >
template<>
struct MD5Sum< ::node_manager::nodeInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::node_manager::nodeInfo >::value();
  }
  static const char* value(const ::node_manager::nodeInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_manager::nodeInfoRequest> should match
// service_traits::DataType< ::node_manager::nodeInfo >
template<>
struct DataType< ::node_manager::nodeInfoRequest>
{
  static const char* value()
  {
    return DataType< ::node_manager::nodeInfo >::value();
  }
  static const char* value(const ::node_manager::nodeInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::node_manager::nodeInfoResponse> should match
// service_traits::MD5Sum< ::node_manager::nodeInfo >
template<>
struct MD5Sum< ::node_manager::nodeInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::node_manager::nodeInfo >::value();
  }
  static const char* value(const ::node_manager::nodeInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_manager::nodeInfoResponse> should match
// service_traits::DataType< ::node_manager::nodeInfo >
template<>
struct DataType< ::node_manager::nodeInfoResponse>
{
  static const char* value()
  {
    return DataType< ::node_manager::nodeInfo >::value();
  }
  static const char* value(const ::node_manager::nodeInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODE_MANAGER_MESSAGE_NODEINFO_H
