// Generated by gencpp from file pc_merge/mergePc.msg
// DO NOT EDIT!


#ifndef PC_MERGE_MESSAGE_MERGEPC_H
#define PC_MERGE_MESSAGE_MERGEPC_H

#include <ros/service_traits.h>


#include <pc_merge/mergePcRequest.h>
#include <pc_merge/mergePcResponse.h>


namespace pc_merge
{

struct mergePc
{

typedef mergePcRequest Request;
typedef mergePcResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mergePc
} // namespace pc_merge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pc_merge::mergePc > {
  static const char* value()
  {
    return "de99575f7cba9c0362917ec861ff5f7b";
  }

  static const char* value(const ::pc_merge::mergePc&) { return value(); }
};

template<>
struct DataType< ::pc_merge::mergePc > {
  static const char* value()
  {
    return "pc_merge/mergePc";
  }

  static const char* value(const ::pc_merge::mergePc&) { return value(); }
};


// service_traits::MD5Sum< ::pc_merge::mergePcRequest> should match
// service_traits::MD5Sum< ::pc_merge::mergePc >
template<>
struct MD5Sum< ::pc_merge::mergePcRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pc_merge::mergePc >::value();
  }
  static const char* value(const ::pc_merge::mergePcRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pc_merge::mergePcRequest> should match
// service_traits::DataType< ::pc_merge::mergePc >
template<>
struct DataType< ::pc_merge::mergePcRequest>
{
  static const char* value()
  {
    return DataType< ::pc_merge::mergePc >::value();
  }
  static const char* value(const ::pc_merge::mergePcRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pc_merge::mergePcResponse> should match
// service_traits::MD5Sum< ::pc_merge::mergePc >
template<>
struct MD5Sum< ::pc_merge::mergePcResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pc_merge::mergePc >::value();
  }
  static const char* value(const ::pc_merge::mergePcResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pc_merge::mergePcResponse> should match
// service_traits::DataType< ::pc_merge::mergePc >
template<>
struct DataType< ::pc_merge::mergePcResponse>
{
  static const char* value()
  {
    return DataType< ::pc_merge::mergePc >::value();
  }
  static const char* value(const ::pc_merge::mergePcResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PC_MERGE_MESSAGE_MERGEPC_H
