// Generated by gencpp from file pc_merge/mergePcResponse.msg
// DO NOT EDIT!


#ifndef PC_MERGE_MESSAGE_MERGEPCRESPONSE_H
#define PC_MERGE_MESSAGE_MERGEPCRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pc_merge
{
template <class ContainerAllocator>
struct mergePcResponse_
{
  typedef mergePcResponse_<ContainerAllocator> Type;

  mergePcResponse_()
    : ok(false)  {
    }
  mergePcResponse_(const ContainerAllocator& _alloc)
    : ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::pc_merge::mergePcResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pc_merge::mergePcResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mergePcResponse_

typedef ::pc_merge::mergePcResponse_<std::allocator<void> > mergePcResponse;

typedef boost::shared_ptr< ::pc_merge::mergePcResponse > mergePcResponsePtr;
typedef boost::shared_ptr< ::pc_merge::mergePcResponse const> mergePcResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pc_merge::mergePcResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pc_merge::mergePcResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pc_merge::mergePcResponse_<ContainerAllocator1> & lhs, const ::pc_merge::mergePcResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pc_merge::mergePcResponse_<ContainerAllocator1> & lhs, const ::pc_merge::mergePcResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pc_merge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pc_merge::mergePcResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pc_merge::mergePcResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pc_merge::mergePcResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pc_merge::mergePcResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pc_merge::mergePcResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pc_merge::mergePcResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pc_merge::mergePcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::pc_merge::mergePcResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::pc_merge::mergePcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pc_merge/mergePcResponse";
  }

  static const char* value(const ::pc_merge::mergePcResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pc_merge::mergePcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"\n"
;
  }

  static const char* value(const ::pc_merge::mergePcResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pc_merge::mergePcResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mergePcResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pc_merge::mergePcResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pc_merge::mergePcResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PC_MERGE_MESSAGE_MERGEPCRESPONSE_H
