(cl:in-package thi_vision-srv)
(cl:export '(POINTCLOUDFILE-VAL
          POINTCLOUDFILE
          FILETYPE-VAL
          FILETYPE
          WORKPIECE-VAL
          WORKPIECE
          PRESS-VAL
          PRESS
          WIDTH-VAL
          WIDTH
          GROOVEWIDTH-VAL
          GROOVEWIDTH
          AVOIDLEFT-VAL
          AVOIDLEFT
          AVOIDRIGHT-VAL
          AVOIDRIGHT
          LENGTH-VAL
          LENGTH
          ANGLELEFT-VAL
          ANGLELEFT
          ANGLERIGHT-VAL
          ANGLERIGHT
          LISTPCAREAS-VAL
          LISTPCAREAS
          TRACKS-VAL
          TRACKS
          OK-VAL
          OK
))