// Generated by gencpp from file pc_image_save/savePcAndImage.msg
// DO NOT EDIT!


#ifndef PC_IMAGE_SAVE_MESSAGE_SAVEPCANDIMAGE_H
#define PC_IMAGE_SAVE_MESSAGE_SAVEPCANDIMAGE_H

#include <ros/service_traits.h>


#include <pc_image_save/savePcAndImageRequest.h>
#include <pc_image_save/savePcAndImageResponse.h>


namespace pc_image_save
{

struct savePcAndImage
{

typedef savePcAndImageRequest Request;
typedef savePcAndImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct savePcAndImage
} // namespace pc_image_save


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pc_image_save::savePcAndImage > {
  static const char* value()
  {
    return "dd3b3b413ecc248d44e5417f1e4d808b";
  }

  static const char* value(const ::pc_image_save::savePcAndImage&) { return value(); }
};

template<>
struct DataType< ::pc_image_save::savePcAndImage > {
  static const char* value()
  {
    return "pc_image_save/savePcAndImage";
  }

  static const char* value(const ::pc_image_save::savePcAndImage&) { return value(); }
};


// service_traits::MD5Sum< ::pc_image_save::savePcAndImageRequest> should match
// service_traits::MD5Sum< ::pc_image_save::savePcAndImage >
template<>
struct MD5Sum< ::pc_image_save::savePcAndImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pc_image_save::savePcAndImage >::value();
  }
  static const char* value(const ::pc_image_save::savePcAndImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pc_image_save::savePcAndImageRequest> should match
// service_traits::DataType< ::pc_image_save::savePcAndImage >
template<>
struct DataType< ::pc_image_save::savePcAndImageRequest>
{
  static const char* value()
  {
    return DataType< ::pc_image_save::savePcAndImage >::value();
  }
  static const char* value(const ::pc_image_save::savePcAndImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pc_image_save::savePcAndImageResponse> should match
// service_traits::MD5Sum< ::pc_image_save::savePcAndImage >
template<>
struct MD5Sum< ::pc_image_save::savePcAndImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pc_image_save::savePcAndImage >::value();
  }
  static const char* value(const ::pc_image_save::savePcAndImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pc_image_save::savePcAndImageResponse> should match
// service_traits::DataType< ::pc_image_save::savePcAndImage >
template<>
struct DataType< ::pc_image_save::savePcAndImageResponse>
{
  static const char* value()
  {
    return DataType< ::pc_image_save::savePcAndImage >::value();
  }
  static const char* value(const ::pc_image_save::savePcAndImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PC_IMAGE_SAVE_MESSAGE_SAVEPCANDIMAGE_H
