// Generated by gencpp from file pc_image_save/savePcAndImageResponse.msg
// DO NOT EDIT!


#ifndef PC_IMAGE_SAVE_MESSAGE_SAVEPCANDIMAGERESPONSE_H
#define PC_IMAGE_SAVE_MESSAGE_SAVEPCANDIMAGERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pc_image_save
{
template <class ContainerAllocator>
struct savePcAndImageResponse_
{
  typedef savePcAndImageResponse_<ContainerAllocator> Type;

  savePcAndImageResponse_()
    : ok(false)  {
    }
  savePcAndImageResponse_(const ContainerAllocator& _alloc)
    : ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct savePcAndImageResponse_

typedef ::pc_image_save::savePcAndImageResponse_<std::allocator<void> > savePcAndImageResponse;

typedef boost::shared_ptr< ::pc_image_save::savePcAndImageResponse > savePcAndImageResponsePtr;
typedef boost::shared_ptr< ::pc_image_save::savePcAndImageResponse const> savePcAndImageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pc_image_save::savePcAndImageResponse_<ContainerAllocator1> & lhs, const ::pc_image_save::savePcAndImageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pc_image_save::savePcAndImageResponse_<ContainerAllocator1> & lhs, const ::pc_image_save::savePcAndImageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pc_image_save

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::pc_image_save::savePcAndImageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pc_image_save/savePcAndImageResponse";
  }

  static const char* value(const ::pc_image_save::savePcAndImageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"\n"
;
  }

  static const char* value(const ::pc_image_save::savePcAndImageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct savePcAndImageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pc_image_save::savePcAndImageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pc_image_save::savePcAndImageResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PC_IMAGE_SAVE_MESSAGE_SAVEPCANDIMAGERESPONSE_H
