# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from thi_vision/track.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import thi_vision.msg

class track(genpy.Message):
  _md5sum = "7c10583178550886efa4f5156f56c1e6"
  _type = "thi_vision/track"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """pose[] track

================================================================================
MSG: thi_vision/pose
position point
orientation angle

================================================================================
MSG: thi_vision/position
float32 x
float32 y
float32 z

================================================================================
MSG: thi_vision/orientation
float32 a
float32 b
float32 c
"""
  __slots__ = ['track']
  _slot_types = ['thi_vision/pose[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       track

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(track, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.track is None:
        self.track = []
    else:
      self.track = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.track)
      buff.write(_struct_I.pack(length))
      for val1 in self.track:
        _v1 = val1.point
        _x = _v1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v2 = val1.angle
        _x = _v2
        buff.write(_get_struct_3f().pack(_x.a, _x.b, _x.c))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.track is None:
        self.track = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.track = []
      for i in range(0, length):
        val1 = thi_vision.msg.pose()
        _v3 = val1.point
        _x = _v3
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        _v4 = val1.angle
        _x = _v4
        start = end
        end += 12
        (_x.a, _x.b, _x.c,) = _get_struct_3f().unpack(str[start:end])
        self.track.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.track)
      buff.write(_struct_I.pack(length))
      for val1 in self.track:
        _v5 = val1.point
        _x = _v5
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v6 = val1.angle
        _x = _v6
        buff.write(_get_struct_3f().pack(_x.a, _x.b, _x.c))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.track is None:
        self.track = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.track = []
      for i in range(0, length):
        val1 = thi_vision.msg.pose()
        _v7 = val1.point
        _x = _v7
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        _v8 = val1.angle
        _x = _v8
        start = end
        end += 12
        (_x.a, _x.b, _x.c,) = _get_struct_3f().unpack(str[start:end])
        self.track.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
